# Generated by Django 6.0.5 on 2026-05-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
    ]
