# Generated by Django 6.0.5 on 2026-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_remove_recipient_full_name_recipient_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
