# Generated by Django 6.0.5 on 2026-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0010_recipient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='label',
            field=models.CharField(default='⬛', max_length=255),
        ),
    ]
