# Generated by Django 6.0.5 on 2026-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_recipient_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='last_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
