# Generated by Django 6.0.5 on 2026-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0012_recipient_last_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Логотип'),
        ),
    ]
