# Generated by Django 6.0.5 on 2026-05-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0013_message_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL логотипа'),
        ),
        migrations.AlterField(
            model_name='message',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='message_logos/'),
        ),
    ]
