# Generated by Django 6.0.5 on 2026-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0014_message_logo_url_alter_message_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
